steps:
  # Step to retrieve GITHUB_PAT using gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret=GITHUB_PAT > /workspace/github_pat
        cat /workspace/github_pat # Debug: Print the GITHUB_PAT value

  # Step to set up npm authentication and install dependencies
  - name: 'node:18'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        echo "//npm.pkg.github.com/:_authToken=$(cat /workspace/github_pat)" > ~/.npmrc
        cat ~/.npmrc # Debug: Check .npmrc content

  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        docker build \
          --build-arg REACT_APP_API_BASE_URL=${_REACT_APP_API_BASE_URL} \
          --build-arg GITHUB_PAT="$(cat /workspace/github_pat)" \
          -t asia-southeast1-docker.pkg.dev/$PROJECT_ID/dubai-task-frontend/frontend:$SHORT_SHA .


  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/dubai-task-frontend/frontend:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" pre-kubernetes.yaml | \
        sed "s/COMMIT_SHA/${SHORT_SHA}/g" > kubernetes.yaml

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes.yaml
      - --location=${_GKE_ZONE}
      - --cluster=${_TARGET_ENV}-cluster
      - --project=${_GCLOUD_PROJECT_ID}

options:
  logging: CLOUD_LOGGING_ONLY
